# Generated by Django 4.2.5 on 2023-09-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPZERO', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeleteModels',
        ),
        migrations.DeleteModel(
            name='RetrieveModels',
        ),
        migrations.DeleteModel(
            name='UpdateModels',
        ),
    ]
